export const PROFILE_CONSTANTS = {
	MAX_LEGAL_NAME_LENGTH: 150,
	MAX_PHONE_LENGTH: 30,
	MAX_HEADLINE_LENGTH: 180,
	MAX_BIO_LENGTH: 5000,
	MAX_SKILLS: 50,
	MAX_SKILL_LENGTH: 60,
	MAX_JOB_TITLE_LENGTH: 150,
} as const;

export const PROFILE_UPLOAD_ASSET_TYPES = [
	"PROFILE_IMAGE",
	"CANDIDATE_RESUME",
	"COMPANY_LOGO",
] as const;
