export const INVITATION_CONSTANTS = {
	TOKEN_BYTES: 32,
	TOKEN_HEX_LENGTH: 64,
	EXPIRES_IN_HOURS: 168,
	MAX_RECIPIENTS_PER_REQUEST: 1000,
	NOTIFICATION_TYPE: "ASSESSMENT_INVITATION_EMAIL",
	NOTIFICATION_ENTITY_TYPE: "INVITATION",
	RECOVERY_BATCH_SIZE: 1000,
	RECOVERY_INTERVAL_MS: 60000,
} as const;
