export const ATTEMPT_CONSTANTS = {
	MAX_TEXT_ANSWER_LENGTH: 50000,
	MAX_CODE_ANSWER_LENGTH: 200000,
	MAX_LANGUAGE_LENGTH: 60,
	MAX_SELECTED_OPTIONS: 50,
	MAX_PROCTOR_METADATA_BYTES: 20480,
	EXPIRY_BATCH_SIZE: 100,
	EXPIRY_CRON: "*/10 * * * * *",
} as const;
