export const AUDIT_ACTIONS = {
	QUESTION_CREATED: "QUESTION_CREATED",
	QUESTION_UPDATED: "QUESTION_UPDATED",
	QUESTION_DUPLICATED: "QUESTION_DUPLICATED",
	QUESTION_DELETED: "QUESTION_DELETED",
} as const;

export const AUDIT_ENTITY_TYPES = {
	QUESTION: "QUESTION",
} as const;
