export const AUDIT_ACTIONS = {
	QUESTION_CREATED: "QUESTION_CREATED",
	QUESTION_UPDATED: "QUESTION_UPDATED",
	QUESTION_DUPLICATED: "QUESTION_DUPLICATED",
	QUESTION_DELETED: "QUESTION_DELETED",

	ASSESSMENT_CREATED: "ASSESSMENT_CREATED",
	ASSESSMENT_UPDATED: "ASSESSMENT_UPDATED",
	ASSESSMENT_DELETED: "ASSESSMENT_DELETED",
	ASSESSMENT_QUESTION_ADDED: "ASSESSMENT_QUESTION_ADDED",
	ASSESSMENT_QUESTION_UPDATED: "ASSESSMENT_QUESTION_UPDATED",
	ASSESSMENT_QUESTION_REMOVED: "ASSESSMENT_QUESTION_REMOVED",
	ASSESSMENT_QUESTIONS_REORDERED: "ASSESSMENT_QUESTIONS_REORDERED",
	ASSESSMENT_CREDIT_CONSUMED: "ASSESSMENT_CREDIT_CONSUMED",
	ASSESSMENT_PUBLISHED: "ASSESSMENT_PUBLISHED",
	ASSESSMENT_CLOSED: "ASSESSMENT_CLOSED",

	APPLICATION_CREATED: "APPLICATION_CREATED",
	APPLICATION_SHORTLISTED: "APPLICATION_SHORTLISTED",
	APPLICATION_REJECTED: "APPLICATION_REJECTED",

	INVITATION_CREATED: "INVITATION_CREATED",
	INVITATION_RESENT: "INVITATION_RESENT",
	INVITATION_REVOKED: "INVITATION_REVOKED",
	INVITATION_ACCEPTED: "INVITATION_ACCEPTED",

	ATTEMPT_STARTED: "ATTEMPT_STARTED",
	ATTEMPT_SUBMITTED: "ATTEMPT_SUBMITTED",
	ATTEMPT_AUTO_SUBMITTED: "ATTEMPT_AUTO_SUBMITTED",
	ATTEMPT_FLAGGED_SUSPICIOUS: "ATTEMPT_FLAGGED_SUSPICIOUS",
} as const;

export const AUDIT_ENTITY_TYPES = {
	QUESTION: "QUESTION",
	ASSESSMENT: "ASSESSMENT",
	ASSESSMENT_QUESTION: "ASSESSMENT_QUESTION",
	CREDIT_GRANT: "CREDIT_GRANT",
	APPLICATION: "APPLICATION",
	INVITATION: "INVITATION",
	ATTEMPT: "ATTEMPT",
} as const;